/**
 * This struct is used to describe the recipient of a document and indicate if the recipient is requested to
 * sign the document.
 * 
 * @property fingerprint The fingerprint of the recipient's key.
 * @property signatureRequested Indicates whether a signature from this recipient has been requested.
 */
export type Recipient = {
    fingerprint: `0x${string}`;
    signatureRequested: boolean;
}

/**
 * Enum used by Notification events to help users understand what kind of event is related to the notification.
 */
export enum EventType {
    DOCUMENT = 0, // The notification is caused by a user sending a document to peers (Document).
    COPY = 1 // The notification is caused by a user sending a certified copy of a document (Copy).
}

/**
 * Base type representing common properties of all event logs emitted by the Web3Doc smart contract.
 * 
 * @property transactionHash The hash of the transaction that emitted the event.
 * @property blockNumber The number of the block that contains the transaction.
 * @property blockHash The hash of the block that contains the transaction.
 * @property blockTimestamp The timestamp of the block that contains the transaction.
 */
type BaseLog = {
    transactionHash: `0x${string}`;
    blockNumber: bigint;
    blockHash: `0x${string}`;
    blockTimestamp: Date;
}

/**
 * Type representing a Document event emitted when a user sends a document to peers.
 *
 * @property id Unique ID generated by the smart contract.
 * @property emitter The fingerprint of the key used to produce the signature.
 * @property dochash The keccak256 hash of the document.
 * @property signature An OpenPGP message which contains the detached signature made over the document.
 * @property document An optional OpenPGP message which contains the (encrypted) document.
 * @property uri An optional URI which can be used to download the document from an off-chain storage like IPFS, S3, SFTP, ...
 * @property mimeType Optional, The MIME type of the document and additional attributes (RFC6838)
 */
export type DocumentLog = BaseLog & {

    id: bigint | undefined;
    emitter: `0x${string}` | undefined;
    dochash: `0x${string}` | undefined;
    signature: `0x${string}` | undefined;
    document: `0x${string}` | undefined;
    uri: string | undefined;
    mimeType: string | undefined;
};

/**
 * Type representing a Copy event emitted when a user sends a certified copy of a document.
 * 
 * @property copy The unique ID assigned to the copy by the smart contract.
 * @property original The ID of the original document assigned by the smart contract.
 * @property emitter The fingerprint of the key used by the emitter.
 * @property document The binary OpenPGP message containing the document itself.
 * @property uri The URI which can be used to download the binary OpenPGP message containing the document from an off-chain storage.
 */
export type CopyLog = BaseLog & {
    copy?: bigint | undefined;
    original?: bigint | undefined;
    emitter?: `0x${string}` | undefined;
    document?: `0x${string}` | undefined;
    uri?: string | undefined;
};

/**
 * Type representing a Notification event emitted to warn recipients that a new document has been sent to them.
 *
 * @property id The unique ID of the document that has been sent.
 * @property emitter The fingerprint of the key used by the emitter.
 * @property recipient The fingerprint of the key of the recipient.
 * @property source The type of event that has caused this notification (publication, response or copy).
 * @property signatureRequested If true, the recipient is prompted by the emitter to sign the document.
 */
export type NotificationLog = BaseLog & {
    id: bigint | undefined;
    emitter: `0x${string}` | undefined;
    recipient: `0x${string}` | undefined;
    source: EventType | undefined;
    signatureRequested: boolean | undefined;
};

/**
 * Type representing a Signature event emitted when a user signs a document.
 *
 * @property id The unique ID of the document being signed.
 * @property emitter The fingerprint of the key used to create the signature.
 * @property signature The binary OpenPGP message which contains the detached signature over the document.
 */
export type SignatureLog = BaseLog & {
    id: bigint | undefined;
    emitter: `0x${string}` | undefined;
    signature: `0x${string}` | undefined;
};

/**
 * Type representing a Timestamp event emitted when a user timestamps a document.
 *
 * @property id A unique ID generated by the smart contract for this timestamp event.
 * @property emitter The fingerprint of the public key used to create the signature.
 * @property dochash The keccak256 hash of the document used to look up the timestamp and to verify the document's integrity.
 * @property signature A detached binary OpenPGP signature created over the keccak256 hash of the document.
 */
export type TimestampLog = BaseLog & {
    id: bigint | undefined;
    emitter: `0x${string}` | undefined;
    dochash: `0x${string}` | undefined;
    signature: `0x${string}` | undefined;
};
