// SPDX-License-Identifier: Business Source License 1.1
pragma solidity ^0.8.24;

import "./IWeb3PGP.sol";

/**
 * @title IWeb3Doc
 * @author degengineering.eth
 * @notice This interface defines events and functions used timestamp, sign and send documents through the blockchain
 * such as electronic invoices (UBL & PEPPOL BIS) and other documents (UBL - credit notes, purchase orders, ...).
 */
interface IWeb3Doc {

    /*****************************************************************************************************************/
    /* STRUCTS                                                                                                       */
    /*****************************************************************************************************************/

    /**
     * @dev This struct is used to describe the recipient of a document and indicate if the recipient is requested to 
     * sign the document.
     */
    struct Recipient {
        /**
         * @dev The fingerprints of the key of the recipient to be notified. Must exist within the Web3PGP contract.
         */
        bytes32 fingerprint;

        /**
         * @dev Indicates if the recipient is requested by the emitter to sign the document.
         */
        bool signatureRequested;  
    }

    /*****************************************************************************************************************/
    /* ENUMS                                                                                                         */
    /*****************************************************************************************************************/

    /**
     * Enum used by Notification events to help users understanding what type of event has triggered the notification.
     */
    enum EventType {
        PUBLICATION, // 0 - The notification is caused by a publication (Publication).
        COPY, // 1 - The notification is caused by a certified copy of a previously published document (Copy).
        RESPONSE // 2 - The notification is caused by a response to a publication (Response).
    }

    /*****************************************************************************************************************/
    /* EVENTS                                                                                                        */
    /*****************************************************************************************************************/

    /**
     * Event emitted when a user publishes a new detached signature and, optionally, the signed document.
     * 
     * @param id Unique ID generated by the smart contract.
     * @param emitter The fingerprint of the key used to produce the signature. Must exist on W3PGP contract.
     * @param dochash The keccak256 hash of the document. This is used to find the publication from the document.
     * @param signature An OpenPGP message which contains the detached signature over the document (cleartext).
     * @param document An optional OpenPGP message which contains the (encrypted) document linked to the detached signature.
     * @param uri An optional URI which can be used to download the document from an off-chain storage like IPFS, S3, SFTP, ...
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838)
     *  
     * @notice This event is used to record a detached signature and, optionally, the document data. Users must extract
     * the signature from the OpenPGP message to verify the document. The document can be stored on-chain in a separate
     * OpenPGP message. The URI can be used to download the document from an off-chain storage.
     * 
     * The OpenPGP message containing the signature may be compressed, but must not be encrypted, to ensure that all users can 
     * verify the signature against the document or any of its copies at any time. The signature must be a detached signature, 
     * created over a binary OpenPGP message that represents the raw bytes of the document.
     * 
     * The optional OpenPGP message containing the document should be encrypted to ensure that it can only be read by the intended
     * recipients. It may also be compressed to reduce gas costs. Users must decrypt and decompress the message before verifying 
     * the document using the detached signature. Storing the document on-chain ensures that it is always available and cannot be
     * lost. Additionally, the on-chain record can serve as proof of delivery.
     * 
     * The optional URI can be used to download the document from off-chain storage. No assumptions are made about the storage system
     * — it may be IPFS, S3, Redis, or any other backend. Users are responsible for managing both access control and data persistence.
     * The URI is expected to point to a location where the document is available as an encrypted OpenPGP message, which may also be 
     * compressed to reduce size. Once decrypted (and decompressed, if applicable), users must verify the document using the detached
     * signature and the emitter’s public key.
     * 
     * The smart contract does not perform any validation of the data. It is the responsibility of users to verify the authenticity and
     * integrity of the data by validating the on-chain OpenPGP messages — including the public key, the detached signature, and the 
     * associated document — before trusting or using them.
     * 
     * @dev MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor 
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely 
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     */
    event Publication(uint256 indexed id, bytes32 indexed emitter, bytes32 indexed dochash, bytes signature, bytes document, string uri, string mimeType);

    /**
     * Event emitted to warn the recipients that a new signature and document have been published. The unique ID can
     * be used to retrieve the signature and the document.
     * 
     * @param id The unique ID of the document that has been published.
     * @param emitter The fingerprint of the key used by the emitter.
     * @param recipient The fingerprint of the key of the recipient.
     * @param source The type of event that has caused this notification (publication, response or copy).
     * @param signatureRequested If true, the recipient is requested by the emitter to sign the document.
     * 
     * @notice This event is used to notify the recipients that a new document has been published. The recipients can use the ID
     * to retrieve the document that has been published as welll as other information like whether this document is a response to a
     * previous document or a copy of a previously published document. Optionnaly, the recipient can be prompted by the emitter to 
     * sign the document.
     */
    event Notification(uint256 indexed id, bytes32 emitter, bytes32 indexed recipient, EventType source, bool indexed signatureRequested);

    /**
     * Event emitted when a user publishes a document which is declared to be a copy of a previously published document. The copy can be
     * published on-chain (document will be set) or off-chain (uri will be set).
     * 
     * @param copy The unique ID assigned to the copy by the smart contract.
     * @param original The ID of the original document.
     * @param emitter The fingerprint of the key used by the emitter.
     * @param document The OpenPGP message containing the document itself. It may be compressed and encrypted (recommended). Used for on-chain storage.
     * @param uri The URI which can be used to download the (compressed and encrypted) OpenPGP message containing the document from an off-chain storage.
     * 
     * @notice This event is used to publish a copy of an existing document and link the copy to the original document. The user is expected to verify
     * the copy is a valid copy of the original document by using the detached signature and the metadata of the original document (from publciation event). 
     * 
     * For security reasons, Copies of copies are not allowed and this is enforced by the smart contract.
     */
    event Copy(uint256 indexed copy, uint256 indexed original, bytes32 indexed emitter, bytes document, string uri);

    /**
     * Additional event emitted on top of a Publication event when a user publishes a document as a response to a previously published document.
     * 
     * @param original The ID of the document which is the subject of the response.
     * @param response The unique ID assigned to the response by the smart contract.
     * @param emitter Fingerprint of the key used by the emitter. Must exist within W3PGP contract.
     * 
     * @notice This event is used to link the response to the original document. The ID of the original document can be used to retrieve the original document
     * and navigate to the top of the response tree.
     */
    event Response(uint256 indexed response, uint256 indexed original, bytes32 indexed emitter);

    /**
     * Emitted when a user signs a document. The signature serves as proof that the document was signed by the emitter.
     * 
     * @param id The unique ID of the document being signed.
     * @param emitter The fingerprint of the key used to create the signature. The contract verifies that this fingerprint exists in Web3PGP.
     * @param signature The OpenPGP message containing the detached signature over the document. This signature is created over the binary OpenPGP message
     * representing the raw bytes of the document. It can be used to verify the document's integrity and prove that the emitter had access to it at the time of signing.
     */
    event Signature(uint256 indexed id, bytes32 indexed emitter, bytes signature);

    /**
     * @dev Emitted when a user timestamps a document.
     *
     * @notice The timestamp serves as cryptographic proof that the document existed at a specific point in time.
     * This is achieved by publishing a detached OpenPGP signature on-chain. The signature can be used to verify
     * the document’s integrity and to demonstrate that the emitter had possession of the document at the time of signing.
     * The document itself is not stored on-chain.
     *
     * @param id A unique ID generated by the smart contract for this timestamp event.
     * @param emitter The keccak256 hash of the fingerprint of the public key used to create the signature (exists in Web3PGP).
     * @param dochash The keccak256 hash of the document used to look up the timestamp and to verify the document’s integrity.
     * @param signature A detached binary OpenPGP signature created over the raw bytes of the keccak256 hash of the document.
     *
     * @dev The event contains all the necessary information to verify the timestamp off-chain:
     * 
     * - The signature must be a valid detached OpenPGP binary signature made with the emitter’s key,
     *   over the raw bytes of the keccak256 hash of the document (not the document itself).
     * 
     * - The emitter field is the keccak256 hash of the fingerprint of the public key that produced the signature.
     *   This fingerprint must be registered in the Web3PGP contract.
     * 
     * - To verify the signature, first retrieve the public key from Web3PGP using the `emitter` hash.
     * - Ensure the public key is valid, not revoked, and not expired. This can be done by checking the associated
     *   revocation events from the Web3PGP contract.
     * 
     * - Finally, verify the signature by building a binary OpenPGP message over the raw 32-byte output
     *   of the keccak256 hash of the original document.
     *
     * WARNING: The signature is made over the raw bytes of the document hash (i.e., the 32-byte output of keccak256),
     * not over the original document itself, nor over a string or hex-encoded version of the hash.
     */
    event Timestamp(uint256 indexed id, bytes32 indexed emitter, bytes32 indexed dochash, bytes signature);

    /*****************************************************************************************************************/
    /* ERRORS                                                                                                        */
    /*****************************************************************************************************************/

    /**
     * Error thrown when the document ID provided by the user does not exist yet.
     * @param id The ID of the document that was not found.
     */
    error DocumentNotFound(uint256 id);

    /**
     * Error thrown when the user tries to publish a copy of a document that is already a copy of another document.
     * @param id The ID of the document that is being copied and that is a copy of another document.
     */
    error DocumentIsACopy(uint256 id);

    /**
     * Error thrown when the user provides the fingerprint of an emitter that is not registered in the Web3PGP contract.
     * @param fingerprint The fingerprint of the emitter that was not found in the Web3PGP contract.
     */
    error EmitterNotFound(bytes32 fingerprint);

    /**
     * Error thrown when the user provides the fingerprint of a recipient that is not registered in the Web3PGP contract.
     * @param fingerprint The fingerprint of the recipient that was not found in the Web3PGP contract.
     */
    error RecipientNotFound(bytes32 fingerprint);

    /*****************************************************************************************************************/
    /* WRITE FUNCTIONS                                                                                               */
    /*****************************************************************************************************************/

    /**
     * Sends a new document and its detached signature on-chain and notifies the specified recipients.
     *
     * Emits a Publication event containing the detached signature and the document itself.
     * Also emits a Notification event for each recipient.
     *
     * @param emitter The fingerprint of the key used to produce the signature. Must be registered in the Web3PGP contract.
     * @param recipients The list of recipients to notify and optionally prompt to sign the document.
     * @param dochash The declared keccak256 hash of the document. This allows users to look up the publication using only the hash of a document.
     * @param signature A detached binary OpenPGP signature of the document. It may be compressed but must not be encrypted.
     * @param document The OpenPGP message containing the document itself. It may be compressed and encrypted (recommended).
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838)
     * 
     * @notice A document can be published on-chain with its detached OpenPGP signature to allow recipients to independently verify the document.
     * Each recipient will receive a Notification event to inform them that a new document has been published. recipients may also be prompted
     * to sign the document. The contract verifies that the emitter and all recipients are registered in the Web3PGP contract before allowing
     * the publication.
     *
     * @dev
     * On-chain publication (preferred):
     * - The document is included in the document parameter as an OpenPGP message.
     * - It may be compressed to reduce gas cost and encrypted to restrict access.
     * - The detached signature is included as a separate OpenPGP message.
     * - The URI field in the Publication event will be empty.
     * - Storing the document on-chain ensures its availability and long-term persistence.
     *
     * Security:
     * - The contract checks that the emitter and all recipients are registered in the Web3PGP contract.
     * - It does not validate the contents of the signature, document or metadata.
     * - Users are responsible for verifying the document and its detached signature before trusting the data.
     * - Users must also ensure the metadata found in the event (e.g., MIME type) matches the content of the decrypted OpenPGP message.
     *
     * About dochash:
     * - This field allows document discovery via its keccak256 hash.
     * - Example use case: a user receives a document without context and wants to verify it.
     * - By computing its keccak256 hash and searching for a matching Publication event, they can retrieve the corresponding detached signature.
     * - The smart contract does not validate that the provided dochash matches the actual content. It is the user's responsibility to ensure consistency.
     * 
     * About MIME types:
     * MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor 
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely 
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     */
    function sendOnChain(
        bytes32 emitter,
        Recipient[] calldata recipients,
        bytes32 dochash,
        bytes calldata signature,
        bytes calldata document,
        string calldata mimeType
    ) external payable;

    /**
     * Sends a new document using an off-chain storage, publishes its detached signature on-chain and notifies the specified recipients.
     *
     * Emits a Publication event containing the detached signature and its download URI.
     * Also emits a Notification event for each recipient.
     *
     * @param emitter The fingerprint of the key used to produce the signature. Must be registered in the Web3PGP contract.
     * @param recipients The list of recipients to notify and optionally prompt to sign the document.
     * @param dochash The declared keccak256 hash of the document. This allows users to look up the publication using only the hash of a document.
     * @param signature A detached binary OpenPGP signature of the document. It may be compressed but must not be encrypted.
     * @param uri A URI which can be used to download the OpenPGP message (compressed and encrypted) containing the document itself.
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838)
     * 
     * @notice A document can be published off-chain. A detached OpenPGP signature must be included and stored on-chain to allow recipients to
     * independently verify the document. Each recipient will receive a Notification event to inform them that a new document has been published.
     * recipients may also be prompted to sign the document. The contract verifies that the emitter and all recipients are registered in the
     * Web3PGP contract before allowing the publication.
     *
     * @dev
     * Off-chain publication:
     * - The document is hosted externally and referenced via the uri.
     * - The document is stored as an OpenPGP message which may be compressed and encrypted.
     * - There is no enforced storage mechanism; users must retrieve and interpret the document themselves.
     * - Systems like IPFS, S3, Redis, or Peppol are all valid options.
     * - The detached signature published on-chain can be used to verify the off-chain document.
     * - It is the users' responsibility to manage access control and data persistence in the off-chain storage.
     * 
     * Security:
     * - The contract checks that the emitter and all recipients are registered in the Web3PGP contract.
     * - It does not validate the contents of the signature, document, or metadata.
     * - Users are responsible for verifying the document and its detached signature before trusting the data.
     * - Users must also ensure the metadata found in the event matches the content of the decrypted OpenPGP message.
     *
     * About dochash:
     * - This field allows document discovery via its keccak256 hash.
     * - Example use case: a user receives a document without context and wants to verify it.
     * - By computing its keccak256 hash and searching for a matching Publication event, they can retrieve the corresponding detached signature.
     * - The smart contract does not validate that the provided `dochash` matches the actual content. It is the user's responsibility to ensure consistency.
     * 
     * About MIME types:
     * MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor 
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely 
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     */
    function sendOffChain(
        bytes32 emitter,
        Recipient[] calldata recipients,
        bytes32 dochash,
        bytes calldata signature,
        string calldata uri,
        string calldata mimeType
    ) external payable;

    /**
     * Publishes a document on-chain declared to be a copy of a previously published original document.
     *
     * Emits:
     * - A Copy event linking the new document to the original and containing the document as an (encrypted and compressed) OpenPGP message.
     * - A Notification event for each recipient.
     *
     * For security reasons, copies of copies are not allowed — this is strictly enforced by the smart contract.
     * 
     * It is up to the user to verify the copy is authentic by retrieving the original document and checking the detached signature and
     * metadata from the Publication event.
     *
     * @param original The ID of the original document being copied. Must reference a valid, non-copy document.
     * @param emitter The fingerprint of the key used to produce the signature.
     * @param recipients The list of recipient key fingerprints to be notified and, optionally, be prompted for a signature.
     * @param document The OpenPGP message containing the copy of the original document. May be compressed and encrypted (recommended). Must be signed by the emitter to prove the origin of the copy.
     * 
     * @notice Publishes a certified copy of an existing document on-chain. The user must use the original document ID to retrieve the Publication event which
     * contains the detached signature and metadata which can be used to verify the authenticity of the copy. Each recipient will receive a Notification event
     * and can be prompted to sign the copy.
     *
     * The contract ensures that:
     * - The original document exists and is not itself a copy.
     * - The emitter and all recipients are registered in the Web3PGP contract.
     *
     * @dev Clients are responsible for verifying that the document is a valid copy of the original using the detached signature and metadata from the Publication
     * event that has been emitted when the original document has been published.
     * 
     * On-chain publication (preferred):
     * - The document is included in the `document` parameter of the Copy event as an (encrypted and compressed) OpenPGP message.
     * - Storing the document on-chain ensures its availability and long-term persistence.
     *
     * Security:
     * - The contract checks that the emitter and all recipients are registered in the Web3PGP contract.
     * - It does not validate the contents of the signature, document, or metadata.
     * - Users are responsible for verifying the copy using the detached signature of the original document before trusting the data.
     * - Users must also ensure the metadata found in the original Publication event (e.g., MIME type, dochash) matches the copy.
     */
    function copyOnChain(
        uint256 original,
        bytes32 emitter,
        Recipient[] calldata recipients,
        bytes calldata document
    ) external payable;

    /**
     * Publishes a document declared to be a copy of a previously published original document using an off-chain storage.
     *
     * Emits:
     * - A Copy event linking the new document to the original and containing a URI pointing to the (encrypted and compressed) OpenPGP message.
     * - A Notification event for each recipient.
     *
     * For security reasons, copies of copies are not allowed — this is strictly enforced by the smart contract.
     * 
     * It is up to the user to verify the copy is authentic by retrieving the original document and checking the detached signature and
     * metadata from the Publication event.
     * 
     * Users are responsible to manage access control and data persistence in the off-chain storage.
     *
     * @param original The ID of the original document being copied. Must reference a valid, non-copy document.
     * @param emitter The fingerprint of the key used to produce the signature.
     * @param recipients The list of recipient key fingerprints to be notified and, optionally, be prompted for a signature.
     * @param uri A URI which can be used to download the OpenPGP message containing the (compressed, encrypted and signed) document itself.
     * 
     * @notice Publishes a certified copy of an existing doocument using an off-chain storage. The user must use the original document ID to retrieve
     * the Publication event which contains the detached signature and metadata which can be used to verify the authenticity of the copy. Each recipient
     * will receive a Notification event and can be prompted to sign the copy.
     *
     * The contract ensures that:
     * - The original document exists and is not itself a copy.
     * - The emitter and all recipients are registered in the Web3PGP contract.
     *
     * @dev Clients are responsible for verifying that the document is a valid copy of the original using the detached signature and metadata from the Publication
     * event that has been emitted when the original document has been published.
     *
     * Off-chain publication:
     * - The document is hosted externally and referenced via the uri.
     * - The document is stored as an OpenPGP message, which may be compressed and encrypted.
     * - There is no enforced storage mechanism; users must retrieve and interpret the document themselves.
     * - Systems like IPFS, S3, Redis, or Peppol are all valid options.
     * - The detached signature published on-chain can be used to verify the off-chain document.
     *
     * Security:
     * - The contract checks that the emitter and all recipients are registered in the Web3PGP contract.
     * - It does not validate the contents of the signature, document, or metadata.
     * - Users are responsible for verifying the copy using the detached signature of the original document before trusting the data.
     * - Users must also ensure the metadata found in the orignal Publciation event (e.g., MIME type, dochash) matches the copy.
     */
    function copyOffChain(
        uint256 original,
        bytes32 emitter,
        Recipient[] calldata recipients,
        string calldata uri
    ) external payable;

    /**
     * Publishes a document on-chain that is a response to a previously published document.
     *
     * Emits:
     * - A Publication event containing the detached signature and the document as an (encrypted and compressed) OpenPGP message.
     * - A Notification event for each recipient.
     * - A `Response` event linking this document to the one it is responding to.
     *
     * @param to The ID of the original document being responded to.
     * @param emitter The fingerprint of the key used to produce the signature. Must be registered in the Web3PGP contract.
     * @param recipients The list of recipients to notify and optionally prompt to sign the document.
     * @param dochash The declared keccak256 hash of the document. This allows users to look up the publication using only the hash of a document.
     * @param signature A detached OpenPGP signature over the document. It may be compressed, but must not be encrypted.
     * @param document The OpenPGP message containing the (compressed and encrypted) document, used for on-chain publication via logs.
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838).
     * 
     * @notice A response document may be published either on-chain or off-chain. Regardless of the storage method,
     * a detached OpenPGP signature must be included to allow recipients to verify the document.
     *
     * Each recipient will receive a Notification event. A Response event will also be emitted to indicate
     * that the newly published document is a response to an existing one.
     *
     * The smart contract ensures:
     * - The original document exists.
     * - The emitter and all recipients are registered in the Web3PGP contract.
     *
     * The smart contract does not validate the content or structure of the document or signature.
     * It is the responsibility of the client to perform full validation and ensure metadata consistency.
     * 
     * About MIME types:
     * MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor 
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely 
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     */
    function respondOnChain(
        uint256 to,
        bytes32 emitter,
        Recipient[] calldata recipients,
        bytes32 dochash,
        bytes calldata signature,
        bytes calldata document,
        string calldata mimeType
    ) external payable;

    /**
     * Publishes a document using an off-chain storage that is a response to a previously published document.
     *
     * Emits:
     * - A Publication event containing the detached signature and the document as an (encrypted and compressed) OpenPGP message.
     * - A Notification event for each recipient.
     * - A Response event linking this document to the one it is responding to.
     *
     * @param to The ID of the original document being responded to.
     * @param emitter The fingerprint of the key used to produce the signature. Must be registered in the Web3PGP contract.
     * @param recipients The list of recipients to notify and optionally prompt to sign the document.
     * @param dochash The declared keccak256 hash of the document. This allows users to look up the publication using only the hash of a document.
     * @param signature A detached OpenPGP signature over the document. It may be compressed, but must not be encrypted.
     * @param uri The URI which can be used to download the OpenPGP message (compressed and encrypted) containing the document itself.
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838).
     * 
     * @notice A response document may be published either on-chain or off-chain. Regardless of the storage method,
     * a detached OpenPGP signature must be included to allow recipients to verify the document.
     *
     * Each recipient will receive a Notification event. A Response event will also be emitted to indicate
     * that the newly published document is a response to an existing one.
     *
     * The smart contract ensures:
     * - The original document exists.
     * - The emitter and all recipients are registered in the Web3PGP contract.
     *
     * The smart contract does not validate the content or structure of the document or signature.
     * It is the responsibility of the client to perform full validation and ensure metadata consistency.
     * 
     * About MIME types:
     * MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor 
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely 
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     */
    function respondOffChain(
        uint256 to,
        bytes32 emitter,
        Recipient[] calldata recipients,
        bytes32 dochash,
        bytes calldata signature,
        string calldata uri,
        string calldata mimeType
    ) external payable;

    /**
     * Publishes a binary detached OpenPGP signature of a document made with the emitter's key. This signature serves as proof that the document 
     * was known and signed by the emitter.
     * 
     * @notice The signature is a detached OpenPGP signature over the document to prove that the document was known and signed by the emitter.
     * 
     * @param id The unique ID of the document that has been signed. This ID is generated by the smart contract when the document is published.
     * @param emitter The fingerprint of the key used to produce the signature. The contract verifies that this fingerprint exists in Web3PGP.
     * @param signature The detached binary OpenPGP signature made over the document.
     * 
     * @dev The signature must be a detached OpenPGP binary signature made with the emitter's key over the raw bytes of the document. The
     * signature must be verified against the document using the emitter's public key, which can be retrieved from the Web3PGP contract.
     */
    function sign(uint256 id, bytes32 emitter, bytes calldata signature) external payable;

    /**
     * Timestamps a document. The timestamp is a way to prove that the document existed at a certain point in time by publishing a detached 
     * signature of the hash of the document on-chain.
     * 
     * @notice The timestamp is a way to prove that the document existed at a certain point in time by publishing a detached signature over 
     * the hash of the document on-chain.
     * 
     * @param emitter The fingerprint of the key used to produce the signature. The contract verifies that this fingerprint exists in Web3PGP.
     * @param dochash The keccak256 hash of the document used to find the timestamp from the document and verify their integrity.
     * @param signature A detached binary OpenPGP signature made over the raw bytes of the keccak256 hash of the document.
     * 
     * @dev The signature must be a detached OpenPGP binary signature made with the emitter's key over the raw bytes of the keccak256 hash of the document.
     * The signature must be verified against the document using the emitter's public key, which can be retrieved from the Web3PGP contract.
     */
    function timestamp(bytes32 emitter, bytes32 dochash, bytes calldata signature) external payable;

    /*****************************************************************************************************************/
    /* READ FUNCTIONS                                                                                                */
    /*****************************************************************************************************************/

    /**
     * @notice Get the address of the Web3PGP contract used as a global public key registry.
     * 
     * @return The address of the Web3PGP contract used by this contract.
     */
    function getWeb3PGPAddress() external view returns (address);

    /**
     * @notice Returns the ID of the original document that the given document is a copy of.
     *
     * @param id The ID of a document that may be a copy of another previously published document.
     * 
     * @return The ID of the original document if the given document is a copy, or 0 if it is not a copy.
     */
    function isCopyOf(uint256 id) external view returns (uint256);

    /**
     * @notice Returns the ID of the original document that the given document is a response to.
     *
     * @param response The ID of a document that may be a response to another document.
     * 
     * @return The ID of the original document if the given document is a response, or 0 if it is not a response.
     */
    function isResponseTo(uint256 response) external view returns (uint256);

    /**
     * @notice Traverses the response chain in reverse, starting from the given response document,
     * and returns the full thread of related document IDs up to the original (initial) document.
     *
     * @param response The ID of the response document from which to begin the rewind operation.
     * @param limit The maximum number of document IDs to include in the response thread.
     *
     * @return An array of document IDs representing the response thread. The first element is the document
     *         to which the given response refers, and the last element is the original document at the root of the thread.
     * 
     * @dev The response chain is strictly linear and acyclic — each response points to a single original
     * and cycles are structurally impossible by design. However, multiple responses can exist and create branches
     * in the response tree. To discover all branches, users must traverse the response tree starting from the original
     * document and follow all responses by querying the logs for `Response` events.
     *
     * The limit parameter is used to cap the number of document IDs returned in the response thread. Loop until an empty array
     * is returned or until the length of the returned array is less than the limit. Use the last response ID from the
     * returned array as the starting point for the next iteration.
     */
    function rewindResponseThread(uint256 response, uint256 limit) external view returns (uint256[] memory);

    /**
     * @notice Returns the block number in which the document or timestamps with the given ID was published.
     *
     * @param id The ID of the document whose block number is to be retrieved.
     *
     * @return The block number in which the document was published. 0 if the document does not exist.
     */
    function getDocumentBlockNumberByID(uint256 id) external view returns (uint256);

    /**
     * @notice Returns the block numbers in which the documents or timestamps with the given IDs were published.
     *
     * @param id The IDs of the documents whose block numbers are to be retrieved.
     *
     * @return The block numbers in which the documents were published. The order of the block numbers corresponds to
     * the order of the document IDs in the input array. If a document does not exist, its block number will be 0.
     */
    function getDocumentBlockNumberByIDBatch(uint256[] calldata id) external view returns (uint256[] memory);

    /**
     * @notice Lists the block numbers when were published the signatures associated with the given document.
     * @param id The ID of the document whose signatures are to be listed.
     * @param start The starting index from which to list signatures (0-based).
     * @param limit The maximum number of signatures to list.
     * @return An array of signature IDs associated with the document.
     * @dev This function supports pagination through the `start` and `limit` parameters to efficiently handle cases
     * where a parent key has a large number of subkeys. Loop until an empty array is returned or until the length of
     * the returned array is less than the limit.
     */
    function listSignatures(
        uint256 id,
        uint256 start,
        uint256 limit
    ) external view returns (uint256[] memory);
}
