// SPDX-License-Identifier: Business Source License 1.1
pragma solidity ^0.8.24;

import "./IWeb3PGP.sol";

/**
 * @title IWeb3Doc
 * @author degengineering.eth
 * @notice Decentralized Electronic Data Interchange (EDI) system for timestamping, signing and exchanging documents.
 * 
 * @dev Design Philosophy:
 * This interface provides a minimal, composable foundation for decentralized document exchange built on Ethereum
 * and OpenPGP cryptography. It intentionally does NOT:
 * - Validate OpenPGP message format or signatures (client-side responsibility)
 * - Enforce document schemas or business logic (composability)
 * - Store complete documents on-chain by default (gas efficiency)
 * - Implement complex workflow orchestration (separation of concerns)
 * 
 * Instead, it provides:
 * - Immutable publication records via event logs
 * - Cryptographic proof of document existence (timestamps)
 * - Peer-to-peer notification system (recipients)
 * - Signature workflow support (acknowledgment/consent)
 * - Certified copy mechanism (document provenance)
 * 
 * Key Features:
 * - Integration with Web3PGP for identity verification
 * - Support for both on-chain and off-chain document storage
 * - Efficient event-driven architecture for indexing and discovery
 * - Flexible enough for invoices, purchase orders, contracts, etc.
 * 
 * Use Cases:
 * - Electronic invoicing (UBL, PEPPOL BIS)
 * - Purchase orders and acknowledgments (UBL, PEPPOL BIS)
 * - Financial documents and statements (ISO 20022)
 * - Legal contracts and agreements
 * - Timestamping and proof-of-existence
 * - IP rights management and licensing
 * 
 * @custom:security All OpenPGP validation and document verification MUST be performed off-chain.
 * @custom:composability Higher-level systems can build workflow automation, schema validation, and business logic.
 * @custom:standards Designed to support UBL (Universal Business Language) and PEPPOL BIS standards.
 */
interface IWeb3Doc {

    /*****************************************************************************************************************/
    /* STRUCTS                                                                                                       */
    /*****************************************************************************************************************/

    /**
     * @dev This struct is used to describe the recipient of a document and indicate if the recipient is requested to
     * sign the document.
     */
    struct Recipient {
        /**
         * @dev The fingerprints of the key of the recipient to be notified. Must exist within the Web3PGP contract.
         */
        bytes32 fingerprint;

        /**
         * @dev Indicates if the recipient is requested by the emitter to sign the document.
         */
        bool signatureRequested;
    }

    /*****************************************************************************************************************/
    /* ENUMS                                                                                                         */
    /*****************************************************************************************************************/

    /**
     * Enum used by Notification events to help users understanding what kind of event is related to the notification.
     */
    enum EventType {
        DOCUMENT, // 0 - The notification is caused by a user sending a document to peers (Document).
        COPY // 1 - The notification is caused by a user sending a certified copy of a document (Copy).
    }

    /*****************************************************************************************************************/
    /* EVENTS                                                                                                        */
    /*****************************************************************************************************************/

    /**
     * Event emitted when a user sends a document to peers.
     *
     * @param id Unique ID generated by the smart contract.
     * @param emitter The fingerprint of the key used to produce the signature.
     * @param dochash The keccak256 hash of the document.
     * @param signature An OpenPGP message which contains the detached signature made over the document.
     * @param document An optional OpenPGP message which contains the (encrypted) document.
     * @param uri An optional URI which can be used to download the document from an off-chain storage like IPFS, S3, SFTP, ...
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838)
     *
     * @notice This event is used to persist the data needed to download, verify and process a document sent by a user. 
     * Optionnally, the (encrypted) document itself can be stored on-chain.
     * 
     * @custom:emitter The emitter is the fingerprint of the public key used to create the detached signature. The contract
     * verifies that this fingerprint exists in Web3PGP.
     * 
     * @custom:dochash The keccak256 hash of the document allows users to look up the publication using only the hash of 
     * a document. This is usefull to find on-chain records when a user receives a document without context and wants to
     * verify it. By computing its keccak256 hash and searching for a matching Publication event, they can retrieve the
     * corresponding detached signature.
     * 
     * @custom:signature The detached signature is a binary OpenPGP message The signature must be a detached signature,
     * created over a binary OpenPGP message that represents the raw bytes of the document.
     * 
     * @custom:document The binary OpenPGP message containing the document itself when on-chain storage is used. It may be 
     * compressed and encrypted (recommended).
     * 
     * @custom:uri The URI can be used to download the (compressed and encrypted) OpenPGP message containing the document
     * from an off-chain storage. No assumptions are made about the storage system — it may be IPFS, S3, Redis, or any other 
     * backend. It is the responsibility of users to manage both access control and data persistence.
     *
     * @custom:mimetype MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     * 
     * @custom:storage The Ethereum log system is used as a cheap storage to store the detached signature, the document 
     * and its metadata.
     *
     * @custom:security The contract does not perform any validation of the data. It is the responsibility of users to
     * validate the data by using the public keys and signatures stored on-chain.
     * 
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    event Document(
        uint256 indexed id,
        bytes32 indexed emitter,
        bytes32 indexed dochash,
        bytes signature,
        bytes document,
        string uri,
        string mimeType
    );

    /**
     * Event emitted when a user send a certified copy of a document.
     * 
     * @param copy The unique ID assigned to the copy by the smart contract.
     * @param original The ID of the original document assigned by the smart contract.
     * @param emitter The fingerprint of the key used by the emitter.
     * @param document The binary OpenPGP message containing the document itself.
     * @param uri The URI which can be used to download the binary OpenPGP message containing the document from an off-chain storage.
     *
     * @notice This event is used to persist a copy of an existing document and link the copy to the original document. The user is expected to verify
     * the copy is a valid copy of the original document by using the detached signature and the metadata of the original document. For security reasons,
     * copies of copies are not allowed and this is enforced by the smart contract.
     * 
     * @custom:emitter The emitter is the fingerprint of the public key used to create the detached signature. The contract
     * verifies that this fingerprint exists in Web3PGP.
     * 
     * @custom:dochash The keccak256 hash of the document allows users to look up the publication using only the hash of 
     * a document. This is usefull to find on-chain records when a user receives a document without context and wants to
     * verify it. By computing its keccak256 hash and searching for a matching Publication event, they can retrieve the
     * corresponding detached signature.
     * 
     * @custom:signature The detached signature is a binary OpenPGP message The signature must be a detached signature,
     * created over a binary OpenPGP message that represents the raw bytes of the document.
     * 
     * @custom:document The binary OpenPGP message containing the document itself when on-chain storage is used. It may be 
     * compressed, encrypted and signed by the emitter (recommended).
     * 
     * @custom:uri The URI can be used to download the (compressed and encrypted) OpenPGP message containing the document
     * from an off-chain storage. No assumptions are made about the storage system — it may be IPFS, S3, Redis, or any other 
     * backend. It is the responsibility of users to manage both access control and data persistence.
     * 
     * @custom:storage The Ethereum log system is used as a cheap storage to store the detached signature, the document 
     * and its metadata.
     *
     * @custom:security The contract does not perform any validation of the data. It is the responsibility of users to
     * validate the data by using the public keys and signatures stored on-chain.
     * 
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    event Copy(uint256 indexed copy, uint256 indexed original, bytes32 indexed emitter, bytes document, string uri);

    /**
     * Event emitted to warn the recipients that a new document has been sent to them. The ID and source can be used to retrieve
     * the event (Document or Copy) which coontains the data to receive the document and verify it.
     *
     * @param id The unique ID of the document that has been sent.
     * @param emitter The fingerprint of the key used by the emitter.
     * @param recipient The fingerprint of the key of the recipient.
     * @param source The type of event that has caused this notification (publication, response or copy).
     * @param signatureRequested If true, the recipient is prompted by the emitter to sign the document.
     *
     * @notice This event is used to notify the recipients that a new document has been sent to them. The recipients can use the ID
     * and source to retrieve the event which contains the data needed to receive and verify the document. Optionally, the recipient
     * can be prompted by the emitter to sign the document, either as acknowledgment or to provide consent.
     * 
     * @custom:emitter The emitter is the fingerprint of the public key used by the emitter to sign the document. The contract
     * verifies that this fingerprint exists in Web3PGP.
     *
     * @custom:recipient The recipient is the fingerprint of the public key of the recipient. The contract verifies that this 
     * fingerprint exists in Web3PGP.
     *
     * @custom:source The source indicates the type of event that has caused this notification (Document or a Copy).
     *
     * @custom:signature-requested If true, the recipient is prompted by the emitter to sign the document either as acknowledgment
     * or to provide consent. All recipients must verify the document and should understand its content before signing it.
     *
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    event Notification(
        uint256 indexed id,
        bytes32 emitter,
        bytes32 indexed recipient,
        EventType source,
        bool indexed signatureRequested
    );

    /**
     * Emitted when a user signs a document. The signature serves as proof that the document was signed by the emitter.
     *
     * @param id The unique ID of the document being signed.
     * @param emitter The fingerprint of the key used to create the signature. The contract verifies that this fingerprint exists in Web3PGP.
     * @param signature The binary OpenPGP message which contains the detached signature over the document.
     *
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    event Signature(uint256 indexed id, bytes32 indexed emitter, bytes signature);

    /**
     * Emitted when a user timestamps a document.
     *
     * @param id A unique ID generated by the smart contract for this timestamp event.
     * @param emitter The fingerprint of the public key used to create the signature (exists in Web3PGP).
     * @param dochash The keccak256 hash of the document used to look up the timestamp and to verify the document’s integrity.
     * @param signature A detached binary OpenPGP signature created over the keccak256 hash of the document.
     *
     * @notice The timestamp serves as cryptographic proof that the document existed at a specific point in time.
     * This is achieved by publishing a detached OpenPGP signature on-chain. The signature can be used to verify
     * the document’s integrity and to demonstrate that the emitter had possession of the document at the time of signing.
     * The document itself is not stored on-chain.
     *
     * @dev The event contains all the necessary information to verify the timestamp off-chain:
     *
     * - The signature must be a valid detached OpenPGP binary signature made with the emitter’s key,
     *   over the raw bytes of the keccak256 hash of the document (not the document itself).
     *
     * - The emitter field is the keccak256 hash of the fingerprint of the public key that produced the signature.
     *   This fingerprint must be registered in the Web3PGP contract.
     *
     * - To verify the signature, first retrieve the public key from Web3PGP using the `emitter` hash.
     *   Ensure the public key is valid, not revoked and not expired. This can be done by checking the associated
     *   revocation events from the Web3PGP contract. Finally, verify the signature using the public key and the
     *   dochash.
     * 
     * - Once the timestamp validity is verified, you can verify a document by computing its keccak256 hash and
     *   comparing it to the dochash stored in the event. If both hashes match, the document is verified and the user
     *   can assume the timestamp applies to the document.
     *
     * WARNING: The signature is made over the raw bytes of the document hash (i.e., the 32-byte output of keccak256),
     * not over the original document itself, nor over a string or hex-encoded version of the hash.
     * 
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    event Timestamp(uint256 indexed id, bytes32 indexed emitter, bytes32 indexed dochash, bytes signature);

    /*****************************************************************************************************************/
    /* ERRORS                                                                                                        */
    /*****************************************************************************************************************/

    /**
     * Error thrown when the document ID provided by the user does not exist yet.
     * @param id The ID of the document that was not found.
     */
    error DocumentNotFound(uint256 id);

    /**
     * Error thrown when the user tries to publish a copy of a document that is already a copy of another document.
     * @param id The ID of the document that is being copied and that is a copy of another document.
     */
    error DocumentIsACopy(uint256 id);

    /**
     * Error thrown when the user provides the fingerprint of an emitter that is not registered in the Web3PGP contract.
     * @param fingerprint The fingerprint of the emitter that was not found in the Web3PGP contract.
     */
    error EmitterNotFound(bytes32 fingerprint);

    /**
     * Error thrown when the user provides the fingerprint of a recipient that is not registered in the Web3PGP contract.
     * @param fingerprint The fingerprint of the recipient that was not found in the Web3PGP contract.
     */
    error RecipientNotFound(bytes32 fingerprint);

    /*****************************************************************************************************************/
    /* WRITE FUNCTIONS                                                                                               */
    /*****************************************************************************************************************/

    /**
     * Sends a document and its detached signature on-chain and notifies the specified recipients.
     *
     * @param emitter The fingerprint of the key used by the emitter to produce the signature.
     * @param recipients The list of recipients to notify and optionally prompt to sign the document.
     * @param dochash The declared keccak256 hash of the document.
     * @param signature A detached binary OpenPGP signature of the document.
     * @param document The binary OpenPGP message which contains the document.
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838)
     *
     * @notice A document can be published on-chain with its detached OpenPGP signature to allow recipients to independently verify the document.
     * Each recipient will receive a Notification event to inform them that a new document has been published. recipients may also be prompted
     * to sign the document. The contract verifies that the emitter and all recipients are registered in the Web3PGP contract before allowing
     * the publication.
     *
     * @dev The document is included in the document parameter as an OpenPGP message. It may be compressed to reduce gas cost and encrypted to 
     * restrict access. The detached signature is included as a separate OpenPGP message and can be used to verify the document. The URI field
     * in the Document event will be empty. Storing the document on-chain ensures its availability and long-term persistence.
     *
     * @custom:security The contract checks that the emitter and all recipients are registered in the Web3PGP contract. It does not validate the 
     * contents of the signature, document or metadata. Users are responsible for verifying the document and its detached signature before trusting
     * the data. Users must also ensure the metadata found in the event (e.g., MIME type) matches the content of the decrypted OpenPGP message.
     *
     * @custom:dochash This field allows users to find blockchain records from the keccak256 hash of a document. Example use case: a user receives
     * a document without context and wants to verify it. By computing its keccak256 hash and searching for a matching Document event, they can 
     * retrieve the corresponding detached signature.
     *
     * @custom:mimetype MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     *
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    function sendOnChain(
        bytes32 emitter,
        Recipient[] calldata recipients,
        bytes32 dochash,
        bytes calldata signature,
        bytes calldata document,
        string calldata mimeType
    ) external payable;

    /**
     * Sends a document using an off-chain channel, publishes its detached signature on-chain and notifies the specified recipients.    
     *
     * @param emitter The fingerprint of the key used to produce the signature.
     * @param recipients The list of recipients to notify and optionally prompt to sign the document.
     * @param dochash The declared keccak256 hash of the document.
     * @param signature A detached binary OpenPGP signature of the document.
     * @param uri A URI which can be used to download the OpenPGP message (compressed and encrypted) which contains the document.
     * @param mimeType Optional, The MIME type of the document and additional attributes (RFC6838)
     *
     * @notice A document can be published off-chain. A detached OpenPGP signature must be included and stored on-chain to allow recipients to
     * independently verify the document. Each recipient will receive a Notification event to inform them that a new document has been published.
     * recipients may also be prompted to sign the document. The contract verifies that the emitter and all recipients are registered in the
     * Web3PGP contract before allowing the publication.
     *
     * @dev The document is hosted externally and referenced via the uri. The document is stored as a binary OpenPGP message which may be compressed
     * and encrypted. There is no enforced storage mechanism; users must retrieve and interpret the document themselves. Systems like IPFS, S3, Redis
     * or Peppol are all valid options. The detached signature published on-chain can be used to verify the document. It is the users' responsibility
     * to upload the document, manage access control and data persistence in the off-chain storage.
     *
     * @custom:security The contract checks that the emitter and all recipients are registered in the Web3PGP contract. It does not validate the 
     * contents of the signature, document or metadata. Users are responsible for verifying the document and its detached signature before trusting
     * the data. Users must also ensure the metadata found in the event (e.g., MIME type) matches the content of the decrypted OpenPGP message.
     *
     * @custom:dochash This field allows users to find blockchain records from the keccak256 hash of a document. Example use case: a user receives
     * a document without context and wants to verify it. By computing its keccak256 hash and searching for a matching Document event, they can 
     * retrieve the corresponding detached signature.
     *
     * @custom:mimetype MIME types and optional parameters (RFC6838) help recipients understand how to process the document. The MIME type specifies
     * the data format (e.g., XML, JSON), while parameters like `schema` can indicate a validation schema or provide additional context.
     *
     * For example: application/xml; schema="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" suggests the document is an XML
     * representation of a UBL invoice.
     *
     * This metadata is optional and should not be fully trusted for security purposes: since it is neither authenticated nor
     * cryptographically verified, it may leak information to attackers or be misleading if manipulated. Clients must not rely
     * solely on it for critical validation or decision-making.
     *
     * Currently, there is no established standard for specifying additional attributes such as schemas or profiles for electronic
     * invoicing in MIME types. Guidance will be provided as standards evolve, and it is the responsibility of developers and protocol
     * participants to adopt and comply with emerging norms.
     *
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    function sendOffChain(
        bytes32 emitter,
        Recipient[] calldata recipients,
        bytes32 dochash,
        bytes calldata signature,
        string calldata uri,
        string calldata mimeType
    ) external payable;

    /**
     * Send a certified copy of a document on-chain.
     *
     * @param original The ID of the original document that is the subject of the copy.
     * @param emitter The fingerprint of the emitter's public key.
     * @param recipients The list of recipient key fingerprints to be notified and, optionally, be prompted for a signature.
     * @param document The binary OpenPGP message containing the copy of the original document.
     *
     * @notice Publishes a certified copy of an existing document on-chain.
     * 
     * @dev The recipient must use the original document ID to retrieve the Document event which contains the detached signature and metadata that
     * can be used to verify the authenticity of the copy. The contract ensures the original document exists and is not itself a copy.
     *
     * @custom:security The contract checks that the emitter and all recipients are registered in the Web3PGP contract. It does not validate the 
     * contents of the signature, document or metadata. Users are responsible for verifying the document and its detached signature before trusting
     * the data. Users must also ensure the metadata found in the event (e.g., MIME type) matches the content of the decrypted OpenPGP message.
     *
     * @custom:dochash This field allows users to find blockchain records from the keccak256 hash of a document. Example use case: a user receives
     * a document without context and wants to verify it. By computing its keccak256 hash and searching for a matching Document event, they can 
     * retrieve the corresponding detached signature.
     * 
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    function copyOnChain(uint256 original, bytes32 emitter, Recipient[] calldata recipients, bytes calldata document)
        external
        payable;

    /**
     * Send a certified copy of a document using an off-chain storage.
     *
     * @param original The ID of the original document being copied. Must reference a valid, non-copy document.
     * @param emitter The fingerprint of the key used to produce the signature.
     * @param recipients The list of recipient key fingerprints to be notified and, optionally, be prompted for a signature.
     * @param uri A URI which can be used to download the OpenPGP message containing the (compressed, encrypted and signed) document itself.
     *
     * @notice Publishes a certified copy of an existing document using an off-chain storage.
     * 
     * @dev The recipient must use the original document ID to retrieve the Document event which contains the detached signature and metadata that
     * can be used to verify the authenticity of the copy. The contract ensures the original document exists and is not itself a copy. There is no
     * enforced storage mechanism; users must retrieve and interpret the document themselves. Systems like IPFS, S3, Redis or Peppol are all valid
     * options. It is the users' responsibility to upload the document, manage access control and data persistence in the off-chain storage.
     *
     * @custom:security The contract checks that the emitter and all recipients are registered in the Web3PGP contract. It does not validate the 
     * contents of the signature, document or metadata. Users are responsible for verifying the document and its detached signature before trusting
     * the data. Users must also ensure the metadata found in the event (e.g., MIME type) matches the content of the decrypted OpenPGP message.
     *
     * @custom:dochash This field allows users to find blockchain records from the keccak256 hash of a document. Example use case: a user receives
     * a document without context and wants to verify it. By computing its keccak256 hash and searching for a matching Document event, they can 
     * retrieve the corresponding detached signature.
     * 
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    function copyOffChain(uint256 original, bytes32 emitter, Recipient[] calldata recipients, string calldata uri)
        external
        payable;

    /**
     * Publishes a binary detached OpenPGP signature of a document made with the emitter's key. This signature serves as proof that the document
     * was known and signed by the emitter.
     *
     * @notice The signature is a detached OpenPGP signature over the document to prove that the document was known and signed by the emitter.
     *
     * @param id The unique ID of the document that has been signed. This ID is generated by the smart contract when the document is published.
     * @param emitter The fingerprint of the key used to produce the signature. The contract verifies that this fingerprint exists in Web3PGP.
     * @param signature The detached binary OpenPGP signature made over the document.
     *
     * @dev The signature must be a detached OpenPGP binary signature made with the emitter's key over the raw bytes of the document. The
     * signature must be verified against the document using the emitter's public key, which can be retrieved from the Web3PGP contract.
     * 
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    function sign(uint256 id, bytes32 emitter, bytes calldata signature) external payable;

    /**
     * Timestamps a document. The timestamp is a way to prove that the document existed at a certain point in time by publishing a detached
     * signature of the hash of the document on-chain.
     *
     * @notice The timestamp is a way to prove that the document existed at a certain point in time by publishing a detached signature over
     * the hash of the document on-chain.
     *
     * @param emitter The fingerprint of the key used to produce the signature. The contract verifies that this fingerprint exists in Web3PGP.
     * @param dochash The keccak256 hash of the document used to find the timestamp from the document and verify their integrity.
     * @param signature A detached binary OpenPGP signature made over the raw bytes of the keccak256 hash of the document.
     *
     * @dev The signature must be a detached OpenPGP binary signature made with the emitter's key over the raw bytes of the keccak256 hash of the document.
     * The signature must be verified against the document using the emitter's public key, which can be retrieved from the Web3PGP contract.
     * 
     * @custom:rfc Currently, RFC 9580 is the reference RFC for OpenPGP but the upcoming "Post-Quantum Cryptography in OpenPGP" is
     * already taken into account https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/12/
     */
    function timestamp(bytes32 emitter, bytes32 dochash, bytes calldata signature) external payable;

    /*****************************************************************************************************************/
    /* READ FUNCTIONS                                                                                                */
    /*****************************************************************************************************************/

    /**
     * @notice Get the address of the Web3PGP contract used as a global public key registry.
     *
     * @return The address of the Web3PGP contract used by this contract.
     */
    function getWeb3PGPAddress() external view returns (address);

    /**
     * @notice Returns the ID of the original document that the given document is a copy of.
     *
     * @param id The ID of a document that may be a copy of another previously published document.
     *
     * @return The ID of the original document if the given document is a copy, or 0 if it is not a copy.
     */
    function isCopyOf(uint256 id) external view returns (uint256);

    /**
     * @notice Returns the block number in which the document or timestamps with the given ID was published.
     *
     * @param id The ID of the document whose block number is to be retrieved.
     *
     * @return The block number in which the document was published. 0 if the document does not exist.
     */
    function getDocumentBlockNumberByID(uint256 id) external view returns (uint256);

    /**
     * @notice Returns the block numbers in which the documents or timestamps with the given IDs were published.
     *
     * @param id The IDs of the documents whose block numbers are to be retrieved.
     *
     * @return The block numbers in which the documents were published. The order of the block numbers corresponds to
     * the order of the document IDs in the input array. If a document does not exist, its block number will be 0.
     */
    function getDocumentBlockNumberByIDBatch(uint256[] calldata id) external view returns (uint256[] memory);

    /**
     * @notice Lists the block numbers when were published the signatures associated with the given document.
     * @param id The ID of the document whose signatures are to be listed.
     * @param start The starting index from which to list signatures (0-based).
     * @param limit The maximum number of signatures to list.
     * @return An array of signature IDs associated with the document.
     * @dev This function supports pagination through the `start` and `limit` parameters to efficiently handle cases
     * where a parent key has a large number of subkeys. Loop until an empty array is returned or until the length of
     * the returned array is less than the limit.
     */
    function listSignatures(uint256 id, uint256 start, uint256 limit) external view returns (uint256[] memory);
}
